/*
Copyright (c) 2011, Los Alamos National Security, LLC
All rights reserved.
Copyright 2011. Los Alamos National Security, LLC. This software was produced under U.S. Government contract DE-AC52-06NA25396 for Los Alamos National Laboratory (LANL),
which is operated by Los Alamos National Security, LLC for the U.S. Department of Energy. The U.S. Government has rights to use, reproduce, and distribute this software.

NEITHER THE GOVERNMENT NOR LOS ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.

If software is modified to produce derivative works, such modified software should be clearly marked, so as not to confuse it with the version available from LANL.

Additionally, redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
·         Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
·         Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other
          materials provided with the distribution.
·         Neither the name of Los Alamos National Security, LLC, Los Alamos National Laboratory, LANL, the U.S. Government, nor the names of its contributors may be used
          to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef VTK_PLANE_FIELD_H_
#define VTK_PLANE_FIELD_H_

#include <piston/choose_container.h>
#include <piston/util/plane_functor.h>
#include <piston/image3d.h>

namespace piston {

template <typename IndexType, typename ValueType, typename Space>
struct vtk_plane_field : public piston::image3d<Space>
{
    typedef piston::image3d<Space> Parent;
    ValueType origin[3];
    ValueType spacing[3];
    ValueType extents[6];

    typedef typename thrust::iterator_traits<typename Parent::GridCoordinatesIterator>::value_type
	    GridCoordinatesType;

    // transfrom grid_coordinates (i, j, k) generated by image3d to shifted and
    // scaled physical_coordinates (x, y, z)
    struct physical_coordinates_functor : public thrust::unary_function<GridCoordinatesType,
								        thrust::tuple<float, float, float> >
    {
        const float xmin, ymin, zmin;
        const float deltax, deltay, deltaz;

        physical_coordinates_functor(float xmin   = 0.0f, float ymin   = 0.0f, float zmin   = 0.0f,
                                     float deltax = 1.0f, float deltay = 1.0f, float deltaz = 1.0f) :
            xmin(xmin), ymin(ymin), zmin(zmin),
            deltax(deltax), deltay(deltay), deltaz(deltaz) {
            std::cout << "physical_coordinates, xmin: " << xmin << " ymin: " << ymin << "zmin: " << zmin << std::endl;
        }

        __host__ __device__
        thrust::tuple<float, float, float> operator()(const GridCoordinatesType& grid_coord) const {
            const float x = xmin + deltax * thrust::get<0>(grid_coord);
            const float y = ymin + deltay * thrust::get<1>(grid_coord);
            const float z = zmin + deltaz * thrust::get<2>(grid_coord);

            return thrust::make_tuple(x, y, z);
        }
    };

    typedef typename thrust::transform_iterator<physical_coordinates_functor,
	    typename Parent::GridCoordinatesIterator> PhysicalCoordinatesIterator;
    PhysicalCoordinatesIterator phys_coordinates_iterator;


    typedef typename detail::choose_container<typename Parent::CountingIterator,
      ValueType>::type PointDataContainer;
    PointDataContainer point_data_vector;
    typedef typename PointDataContainer::iterator PointDataIterator;

    vtk_plane_field(ValueType origin[3], ValueType normal[3], int dims[3],
                    ValueType spacing[3], int extents[6]) :
          Parent(dims[0], dims[1], dims[2]),
          phys_coordinates_iterator(Parent::grid_coordinates_iterator,
                                    physical_coordinates_functor(
                                	    origin[0] + ((ValueType)extents[0] * spacing[0]),
                                	    origin[1] + ((ValueType)extents[2] * spacing[1]),
                                	    origin[2] + ((ValueType)extents[4] * spacing[2]),
                                	    spacing[0], spacing[1], spacing[2])),
          point_data_vector(
              thrust::make_transform_iterator(phys_coordinates_iterator,
                                              plane_functor<IndexType, ValueType>(
                                        	      make_float3(origin[0], origin[1], origin[2]),
                                        	      make_float3(normal[0], normal[1], normal[2]))),
              thrust::make_transform_iterator(phys_coordinates_iterator,
                                              plane_functor<IndexType, ValueType>(
                                        	      make_float3(origin[0], origin[1], origin[2]),
                                        	      make_float3(normal[0], normal[1], normal[2]))) + this->NPoints)
        {
            this->origin[0] = origin[0];
            this->origin[1] = origin[1];
            this->origin[2] = origin[2];

            this->spacing[0] = spacing[0];
            this->spacing[1] = spacing[1];
            this->spacing[2] = spacing[2];

            this->extents[0] = extents[0];
            this->extents[1] = extents[1];
            this->extents[2] = extents[2];
            this->extents[3] = extents[3];
            this->extents[4] = extents[4];
            this->extents[5] = extents[5];
        }

    PhysicalCoordinatesIterator physical_coordinates_begin() {
        return phys_coordinates_iterator;
    }

    PhysicalCoordinatesIterator physical_coordinates_end() {
        return phys_coordinates_iterator+this->NPoints;
    }

    PointDataIterator point_data_begin() {
        return point_data_vector.begin();
    }

    PointDataIterator point_data_end() {
        return point_data_vector.end();
    }

private:
    vtk_plane_field(const vtk_plane_field&);
    vtk_plane_field& operator=(const vtk_plane_field&);
};

}

#endif /* VTK_PLANE_FIELD_H_ */
